name: github-actions
on: [push]
jobs:
  AsyncAction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set ubuntu
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            curl
          pwd
          whoami

      - name: Download lux
        run: |
          sudo mkdir -p /home/src
          curl -L https://github.com/iawia002/lux/releases/download/v0.13.0/lux_0.13.0_Linux_64-bit.tar.gz -o /home/src/lux_0.13.0_Linux_64-bit.tar.gz

      - name: Install lux
        run: |
          sudo tar -zxvf /home/src/lux_0.13.0_Linux_64-bit.tar.gz -C /usr/bin/
          sudo chmod +x /usr/bin/lux
          lux --version

      - name: Start jobs
        run: |
          lux https://www.douyin.com/video/7024851426333527333
          sudo tar -zcvf resource.tar.gz ./*

      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: v1.0.0
          draft: false
          prerelease: false